// <auto-generated />
namespace WorkAndTravelUSA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _13thMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13thMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202001251334238_13-thMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
